version: '3.4'
services:
  ocr.identity-card.service:
    image: ocr.identity-card.service
    container_name: ocr.identity-card.service
    build:
      context: ./OCR.IdentityCard.Service
      dockerfile: Dockerfile
    volumes:
      - ./OCR.IdentityCard.Service/uploads:/app/uploads  
    ports:
      - 8000:8000
    restart: always

